export type ElectronPositionDefinition = {
  side: number
  slot: [number, number]
}

export const ELECTRON_LAYOUT: Record<
  number,
  Array<ElectronPositionDefinition>
> = {
  1: [{ side: 3, slot: [1, 2] }],
  2: [
    { side: 1, slot: [1, 2] },
    { side: 5, slot: [1, 2] },
  ],
  3: [
    { side: 1, slot: [1, 2] },
    { side: 3, slot: [1, 2] },
    { side: 5, slot: [1, 2] },
  ],
  4: [
    { side: 1, slot: [1, 2] },
    { side: 2, slot: [1, 2] },
    { side: 4, slot: [1, 2] },
    { side: 5, slot: [1, 2] },
  ],
  5: [
    { side: 1, slot: [1, 2] },
    { side: 2, slot: [1, 2] },
    { side: 3, slot: [1, 2] },
    { side: 4, slot: [1, 2] },
    { side: 5, slot: [1, 2] },
  ],
  6: [
    { side: 1, slot: [1, 2] },
    { side: 2, slot: [1, 2] },
    { side: 3, slot: [1, 3] },
    { side: 3, slot: [2, 3] },
    { side: 4, slot: [1, 2] },
    { side: 5, slot: [1, 2] },
  ],
  7: [
    { side: 1, slot: [1, 3] },
    { side: 1, slot: [2, 3] },
    { side: 2, slot: [1, 2] },
    { side: 3, slot: [1, 2] },
    { side: 4, slot: [1, 2] },
    { side: 5, slot: [1, 3] },
    { side: 5, slot: [2, 3] },
  ],
  8: [
    { side: 1, slot: [1, 3] },
    { side: 1, slot: [2, 3] },
    { side: 2, slot: [1, 2] },
    { side: 3, slot: [1, 3] },
    { side: 3, slot: [2, 3] },
    { side: 4, slot: [1, 2] },
    { side: 5, slot: [1, 3] },
    { side: 5, slot: [2, 3] },
  ],
  9: [
    { side: 1, slot: [1, 3] },
    { side: 1, slot: [2, 3] },
    { side: 2, slot: [1, 3] },
    { side: 2, slot: [2, 3] },
    { side: 3, slot: [1, 2] },
    { side: 4, slot: [1, 3] },
    { side: 4, slot: [2, 3] },
    { side: 5, slot: [1, 3] },
    { side: 5, slot: [2, 3] },
  ],
  10: [
    { side: 1, slot: [1, 3] },
    { side: 1, slot: [2, 3] },
    { side: 2, slot: [1, 3] },
    { side: 2, slot: [2, 3] },
    { side: 3, slot: [1, 3] },
    { side: 3, slot: [2, 3] },
    { side: 4, slot: [1, 3] },
    { side: 4, slot: [2, 3] },
    { side: 5, slot: [1, 3] },
    { side: 5, slot: [2, 3] },
  ],
  11: [
    { side: 1, slot: [1, 3] },
    { side: 1, slot: [2, 3] },
    { side: 2, slot: [1, 3] },
    { side: 2, slot: [2, 3] },
    { side: 3, slot: [1, 4] },
    { side: 3, slot: [2, 4] },
    { side: 3, slot: [3, 4] },
    { side: 4, slot: [1, 3] },
    { side: 4, slot: [2, 3] },
    { side: 5, slot: [1, 3] },
    { side: 5, slot: [2, 3] },
  ],
  12: [
    { side: 1, slot: [1, 4] },
    { side: 1, slot: [2, 4] },
    { side: 1, slot: [3, 4] },
    { side: 2, slot: [1, 3] },
    { side: 2, slot: [2, 3] },
    { side: 3, slot: [1, 3] },
    { side: 3, slot: [2, 3] },
    { side: 4, slot: [1, 3] },
    { side: 4, slot: [2, 3] },
    { side: 5, slot: [1, 4] },
    { side: 5, slot: [2, 4] },
    { side: 5, slot: [3, 4] },
  ],
  13: [
    { side: 1, slot: [1, 4] },
    { side: 1, slot: [2, 4] },
    { side: 1, slot: [3, 4] },
    { side: 2, slot: [1, 3] },
    { side: 2, slot: [2, 3] },
    { side: 3, slot: [1, 4] },
    { side: 3, slot: [2, 4] },
    { side: 3, slot: [3, 4] },
    { side: 4, slot: [1, 3] },
    { side: 4, slot: [2, 3] },
    { side: 5, slot: [1, 4] },
    { side: 5, slot: [2, 4] },
    { side: 5, slot: [3, 4] },
  ],
  14: [
    { side: 1, slot: [1, 4] },
    { side: 1, slot: [2, 4] },
    { side: 1, slot: [3, 4] },
    { side: 2, slot: [1, 4] },
    { side: 2, slot: [2, 4] },
    { side: 2, slot: [3, 4] },
    { side: 3, slot: [1, 3] },
    { side: 3, slot: [2, 3] },
    { side: 4, slot: [1, 4] },
    { side: 4, slot: [2, 4] },
    { side: 4, slot: [3, 4] },
    { side: 5, slot: [1, 4] },
    { side: 5, slot: [2, 4] },
    { side: 5, slot: [3, 4] },
  ],
  15: [
    { side: 1, slot: [1, 4] },
    { side: 1, slot: [2, 4] },
    { side: 1, slot: [3, 4] },
    { side: 2, slot: [1, 4] },
    { side: 2, slot: [2, 4] },
    { side: 2, slot: [3, 4] },
    { side: 3, slot: [1, 4] },
    { side: 3, slot: [2, 4] },
    { side: 3, slot: [3, 4] },
    { side: 4, slot: [1, 4] },
    { side: 4, slot: [2, 4] },
    { side: 4, slot: [3, 4] },
    { side: 5, slot: [1, 4] },
    { side: 5, slot: [2, 4] },
    { side: 5, slot: [3, 4] },
  ],
  16: [
    { side: 1, slot: [1, 5] },
    { side: 1, slot: [2, 5] },
    { side: 1, slot: [3, 5] },
    { side: 1, slot: [4, 5] },
    { side: 2, slot: [1, 4] },
    { side: 2, slot: [2, 4] },
    { side: 2, slot: [3, 4] },
    { side: 3, slot: [1, 3] },
    { side: 3, slot: [2, 3] },
    { side: 4, slot: [1, 4] },
    { side: 4, slot: [2, 4] },
    { side: 4, slot: [3, 4] },
    { side: 5, slot: [1, 5] },
    { side: 5, slot: [2, 5] },
    { side: 5, slot: [3, 5] },
    { side: 5, slot: [4, 5] },
  ],
  17: [
    { side: 1, slot: [1, 5] },
    { side: 1, slot: [2, 5] },
    { side: 1, slot: [3, 5] },
    { side: 1, slot: [4, 5] },
    { side: 2, slot: [1, 4] },
    { side: 2, slot: [2, 4] },
    { side: 2, slot: [3, 4] },
    { side: 3, slot: [1, 4] },
    { side: 3, slot: [2, 4] },
    { side: 3, slot: [3, 4] },
    { side: 4, slot: [1, 4] },
    { side: 4, slot: [2, 4] },
    { side: 4, slot: [3, 4] },
    { side: 5, slot: [1, 5] },
    { side: 5, slot: [2, 5] },
    { side: 5, slot: [3, 5] },
    { side: 5, slot: [4, 5] },
  ],
  18: [
    { side: 1, slot: [1, 5] },
    { side: 1, slot: [2, 5] },
    { side: 1, slot: [3, 5] },
    { side: 1, slot: [4, 5] },
    { side: 2, slot: [1, 4] },
    { side: 2, slot: [2, 4] },
    { side: 2, slot: [3, 4] },
    { side: 3, slot: [1, 5] },
    { side: 3, slot: [2, 5] },
    { side: 3, slot: [3, 5] },
    { side: 3, slot: [4, 5] },
    { side: 4, slot: [1, 4] },
    { side: 4, slot: [2, 4] },
    { side: 4, slot: [3, 4] },
    { side: 5, slot: [1, 5] },
    { side: 5, slot: [2, 5] },
    { side: 5, slot: [3, 5] },
    { side: 5, slot: [4, 5] },
  ],
  19: [
    { side: 1, slot: [1, 5] },
    { side: 1, slot: [2, 5] },
    { side: 1, slot: [3, 5] },
    { side: 1, slot: [4, 5] },
    { side: 2, slot: [1, 5] },
    { side: 2, slot: [2, 5] },
    { side: 2, slot: [3, 5] },
    { side: 2, slot: [4, 5] },
    { side: 3, slot: [1, 4] },
    { side: 3, slot: [2, 4] },
    { side: 3, slot: [3, 4] },
    { side: 4, slot: [1, 5] },
    { side: 4, slot: [2, 5] },
    { side: 4, slot: [3, 5] },
    { side: 4, slot: [4, 5] },
    { side: 5, slot: [1, 5] },
    { side: 5, slot: [2, 5] },
    { side: 5, slot: [3, 5] },
    { side: 5, slot: [4, 5] },
  ],
  20: [
    { side: 1, slot: [1, 5] },
    { side: 1, slot: [2, 5] },
    { side: 1, slot: [3, 5] },
    { side: 1, slot: [4, 5] },
    { side: 2, slot: [1, 5] },
    { side: 2, slot: [2, 5] },
    { side: 2, slot: [3, 5] },
    { side: 2, slot: [4, 5] },
    { side: 3, slot: [1, 5] },
    { side: 3, slot: [2, 5] },
    { side: 3, slot: [3, 5] },
    { side: 3, slot: [4, 5] },
    { side: 4, slot: [1, 5] },
    { side: 4, slot: [2, 5] },
    { side: 4, slot: [3, 5] },
    { side: 4, slot: [4, 5] },
    { side: 5, slot: [1, 5] },
    { side: 5, slot: [2, 5] },
    { side: 5, slot: [3, 5] },
    { side: 5, slot: [4, 5] },
  ],
  21: [
    { side: 1, slot: [1, 5] },
    { side: 1, slot: [2, 5] },
    { side: 1, slot: [3, 5] },
    { side: 1, slot: [4, 5] },
    { side: 2, slot: [1, 5] },
    { side: 2, slot: [2, 5] },
    { side: 2, slot: [3, 5] },
    { side: 2, slot: [4, 5] },
    { side: 3, slot: [1, 6] },
    { side: 3, slot: [2, 6] },
    { side: 3, slot: [3, 6] },
    { side: 3, slot: [4, 6] },
    { side: 3, slot: [5, 6] },
    { side: 4, slot: [1, 6] },
    { side: 4, slot: [2, 5] },
    { side: 4, slot: [3, 5] },
    { side: 4, slot: [4, 5] },
    { side: 5, slot: [1, 5] },
    { side: 5, slot: [2, 5] },
    { side: 5, slot: [3, 5] },
    { side: 5, slot: [4, 5] },
  ],
  22: [
    { side: 1, slot: [1, 6] },
    { side: 1, slot: [2, 6] },
    { side: 1, slot: [3, 6] },
    { side: 1, slot: [4, 6] },
    { side: 1, slot: [5, 6] },
    { side: 2, slot: [1, 5] },
    { side: 2, slot: [2, 5] },
    { side: 2, slot: [3, 5] },
    { side: 2, slot: [4, 5] },
    { side: 3, slot: [1, 5] },
    { side: 3, slot: [2, 5] },
    { side: 3, slot: [3, 5] },
    { side: 3, slot: [4, 5] },
    { side: 4, slot: [1, 5] },
    { side: 4, slot: [2, 5] },
    { side: 4, slot: [3, 5] },
    { side: 4, slot: [4, 5] },
    { side: 5, slot: [1, 6] },
    { side: 5, slot: [2, 6] },
    { side: 5, slot: [3, 6] },
    { side: 5, slot: [4, 6] },
    { side: 5, slot: [5, 6] },
  ],
  23: [
    { side: 1, slot: [1, 6] },
    { side: 1, slot: [2, 6] },
    { side: 1, slot: [3, 6] },
    { side: 1, slot: [4, 6] },
    { side: 1, slot: [5, 6] },
    { side: 2, slot: [1, 5] },
    { side: 2, slot: [2, 5] },
    { side: 2, slot: [3, 5] },
    { side: 2, slot: [4, 5] },
    { side: 3, slot: [1, 6] },
    { side: 3, slot: [2, 6] },
    { side: 3, slot: [3, 6] },
    { side: 3, slot: [4, 6] },
    { side: 3, slot: [5, 6] },
    { side: 4, slot: [1, 5] },
    { side: 4, slot: [2, 5] },
    { side: 4, slot: [3, 5] },
    { side: 4, slot: [4, 5] },
    { side: 5, slot: [1, 6] },
    { side: 5, slot: [2, 6] },
    { side: 5, slot: [3, 6] },
    { side: 5, slot: [4, 6] },
    { side: 5, slot: [5, 6] },
  ],
  24: [
    { side: 1, slot: [1, 6] },
    { side: 1, slot: [2, 6] },
    { side: 1, slot: [3, 6] },
    { side: 1, slot: [4, 6] },
    { side: 1, slot: [5, 6] },
    { side: 2, slot: [1, 6] },
    { side: 2, slot: [2, 6] },
    { side: 2, slot: [3, 6] },
    { side: 2, slot: [4, 6] },
    { side: 2, slot: [5, 6] },
    { side: 3, slot: [1, 5] },
    { side: 3, slot: [2, 5] },
    { side: 3, slot: [3, 5] },
    { side: 3, slot: [4, 5] },
    { side: 4, slot: [1, 6] },
    { side: 4, slot: [2, 6] },
    { side: 4, slot: [3, 6] },
    { side: 4, slot: [4, 6] },
    { side: 4, slot: [5, 6] },
    { side: 5, slot: [1, 6] },
    { side: 5, slot: [2, 6] },
    { side: 5, slot: [3, 6] },
    { side: 5, slot: [4, 6] },
    { side: 5, slot: [5, 6] },
  ],
  25: [
    { side: 1, slot: [1, 6] },
    { side: 1, slot: [2, 6] },
    { side: 1, slot: [3, 6] },
    { side: 1, slot: [4, 6] },
    { side: 1, slot: [5, 6] },
    { side: 2, slot: [1, 6] },
    { side: 2, slot: [2, 6] },
    { side: 2, slot: [3, 6] },
    { side: 2, slot: [4, 6] },
    { side: 2, slot: [5, 6] },
    { side: 3, slot: [1, 6] },
    { side: 3, slot: [2, 6] },
    { side: 3, slot: [3, 6] },
    { side: 3, slot: [4, 6] },
    { side: 3, slot: [5, 6] },
    { side: 4, slot: [1, 6] },
    { side: 4, slot: [2, 6] },
    { side: 4, slot: [3, 6] },
    { side: 4, slot: [4, 6] },
    { side: 4, slot: [5, 6] },
    { side: 5, slot: [1, 6] },
    { side: 5, slot: [2, 6] },
    { side: 5, slot: [3, 6] },
    { side: 5, slot: [4, 6] },
    { side: 5, slot: [5, 6] },
  ],
  26: [
    { side: 1, slot: [1, 6] },
    { side: 1, slot: [2, 6] },
    { side: 1, slot: [3, 6] },
    { side: 1, slot: [4, 6] },
    { side: 1, slot: [5, 6] },
    { side: 2, slot: [1, 6] },
    { side: 2, slot: [2, 6] },
    { side: 2, slot: [3, 6] },
    { side: 2, slot: [4, 6] },
    { side: 2, slot: [5, 6] },
    { side: 3, slot: [1, 7] },
    { side: 3, slot: [2, 7] },
    { side: 3, slot: [3, 7] },
    { side: 3, slot: [4, 7] },
    { side: 3, slot: [5, 7] },
    { side: 3, slot: [6, 7] },
    { side: 4, slot: [1, 6] },
    { side: 4, slot: [2, 6] },
    { side: 4, slot: [3, 6] },
    { side: 4, slot: [4, 6] },
    { side: 4, slot: [5, 6] },
    { side: 5, slot: [1, 6] },
    { side: 5, slot: [2, 6] },
    { side: 5, slot: [3, 6] },
    { side: 5, slot: [4, 6] },
    { side: 5, slot: [5, 6] },
  ],
  27: [
    { side: 1, slot: [1, 7] },
    { side: 1, slot: [2, 7] },
    { side: 1, slot: [3, 7] },
    { side: 1, slot: [4, 7] },
    { side: 1, slot: [5, 7] },
    { side: 1, slot: [6, 7] },
    { side: 2, slot: [1, 6] },
    { side: 2, slot: [2, 6] },
    { side: 2, slot: [3, 6] },
    { side: 2, slot: [4, 6] },
    { side: 2, slot: [5, 6] },
    { side: 3, slot: [1, 6] },
    { side: 3, slot: [2, 6] },
    { side: 3, slot: [3, 6] },
    { side: 3, slot: [4, 6] },
    { side: 3, slot: [5, 6] },
    { side: 4, slot: [1, 6] },
    { side: 4, slot: [2, 6] },
    { side: 4, slot: [3, 6] },
    { side: 4, slot: [4, 6] },
    { side: 4, slot: [5, 6] },
    { side: 5, slot: [1, 7] },
    { side: 5, slot: [2, 7] },
    { side: 5, slot: [3, 7] },
    { side: 5, slot: [4, 7] },
    { side: 5, slot: [5, 7] },
    { side: 5, slot: [6, 7] },
  ],
  28: [
    { side: 1, slot: [1, 7] },
    { side: 1, slot: [2, 7] },
    { side: 1, slot: [3, 7] },
    { side: 1, slot: [4, 7] },
    { side: 1, slot: [5, 7] },
    { side: 1, slot: [6, 7] },
    { side: 2, slot: [1, 6] },
    { side: 2, slot: [2, 6] },
    { side: 2, slot: [3, 6] },
    { side: 2, slot: [4, 6] },
    { side: 2, slot: [5, 6] },
    { side: 3, slot: [1, 7] },
    { side: 3, slot: [2, 7] },
    { side: 3, slot: [3, 7] },
    { side: 3, slot: [4, 7] },
    { side: 3, slot: [5, 7] },
    { side: 3, slot: [6, 7] },
    { side: 4, slot: [1, 6] },
    { side: 4, slot: [2, 6] },
    { side: 4, slot: [3, 6] },
    { side: 4, slot: [4, 6] },
    { side: 4, slot: [5, 6] },
    { side: 5, slot: [1, 7] },
    { side: 5, slot: [2, 7] },
    { side: 5, slot: [3, 7] },
    { side: 5, slot: [4, 7] },
    { side: 5, slot: [5, 7] },
    { side: 5, slot: [6, 7] },
  ],
  29: [
    { side: 1, slot: [1, 7] },
    { side: 1, slot: [2, 7] },
    { side: 1, slot: [3, 7] },
    { side: 1, slot: [4, 7] },
    { side: 1, slot: [5, 7] },
    { side: 1, slot: [6, 7] },
    { side: 2, slot: [1, 7] },
    { side: 2, slot: [2, 7] },
    { side: 2, slot: [3, 7] },
    { side: 2, slot: [4, 7] },
    { side: 2, slot: [5, 7] },
    { side: 2, slot: [6, 7] },
    { side: 3, slot: [1, 6] },
    { side: 3, slot: [2, 6] },
    { side: 3, slot: [3, 6] },
    { side: 3, slot: [4, 6] },
    { side: 3, slot: [5, 6] },
    { side: 4, slot: [1, 7] },
    { side: 4, slot: [2, 7] },
    { side: 4, slot: [3, 7] },
    { side: 4, slot: [4, 7] },
    { side: 4, slot: [5, 7] },
    { side: 4, slot: [6, 7] },
    { side: 5, slot: [1, 7] },
    { side: 5, slot: [2, 7] },
    { side: 5, slot: [3, 7] },
    { side: 5, slot: [4, 7] },
    { side: 5, slot: [5, 7] },
    { side: 5, slot: [6, 7] },
  ],
  30: [
    { side: 1, slot: [1, 7] },
    { side: 1, slot: [2, 7] },
    { side: 1, slot: [3, 7] },
    { side: 1, slot: [4, 7] },
    { side: 1, slot: [5, 7] },
    { side: 1, slot: [6, 7] },
    { side: 2, slot: [1, 7] },
    { side: 2, slot: [2, 7] },
    { side: 2, slot: [3, 7] },
    { side: 2, slot: [4, 7] },
    { side: 2, slot: [5, 7] },
    { side: 2, slot: [6, 7] },
    { side: 3, slot: [1, 7] },
    { side: 3, slot: [2, 7] },
    { side: 3, slot: [3, 7] },
    { side: 3, slot: [4, 7] },
    { side: 3, slot: [5, 7] },
    { side: 3, slot: [6, 7] },
    { side: 4, slot: [1, 7] },
    { side: 4, slot: [2, 7] },
    { side: 4, slot: [3, 7] },
    { side: 4, slot: [4, 7] },
    { side: 4, slot: [5, 7] },
    { side: 4, slot: [6, 7] },
    { side: 5, slot: [1, 7] },
    { side: 5, slot: [2, 7] },
    { side: 5, slot: [3, 7] },
    { side: 5, slot: [4, 7] },
    { side: 5, slot: [5, 7] },
    { side: 5, slot: [6, 7] },
  ],
  31: [
    { side: 1, slot: [1, 7] },
    { side: 1, slot: [2, 7] },
    { side: 1, slot: [3, 7] },
    { side: 1, slot: [4, 7] },
    { side: 1, slot: [5, 7] },
    { side: 1, slot: [6, 7] },
    { side: 2, slot: [1, 7] },
    { side: 2, slot: [2, 7] },
    { side: 2, slot: [3, 7] },
    { side: 2, slot: [4, 7] },
    { side: 2, slot: [5, 7] },
    { side: 2, slot: [6, 7] },
    { side: 3, slot: [1, 8] },
    { side: 3, slot: [2, 8] },
    { side: 3, slot: [3, 8] },
    { side: 3, slot: [4, 8] },
    { side: 3, slot: [5, 8] },
    { side: 3, slot: [6, 8] },
    { side: 3, slot: [7, 8] },
    { side: 4, slot: [1, 8] },
    { side: 4, slot: [2, 7] },
    { side: 4, slot: [3, 7] },
    { side: 4, slot: [4, 7] },
    { side: 4, slot: [5, 7] },
    { side: 4, slot: [6, 7] },
    { side: 5, slot: [1, 7] },
    { side: 5, slot: [2, 7] },
    { side: 5, slot: [3, 7] },
    { side: 5, slot: [4, 7] },
    { side: 5, slot: [5, 7] },
    { side: 5, slot: [6, 7] },
  ],
  32: [
    { side: 1, slot: [1, 8] },
    { side: 1, slot: [2, 8] },
    { side: 1, slot: [3, 8] },
    { side: 1, slot: [4, 8] },
    { side: 1, slot: [5, 8] },
    { side: 1, slot: [6, 8] },
    { side: 1, slot: [7, 8] },
    { side: 2, slot: [1, 8] },
    { side: 2, slot: [2, 7] },
    { side: 2, slot: [3, 7] },
    { side: 2, slot: [4, 7] },
    { side: 2, slot: [5, 7] },
    { side: 2, slot: [6, 7] },
    { side: 3, slot: [1, 7] },
    { side: 3, slot: [2, 7] },
    { side: 3, slot: [3, 7] },
    { side: 3, slot: [4, 7] },
    { side: 3, slot: [5, 7] },
    { side: 3, slot: [6, 7] },
    { side: 4, slot: [1, 7] },
    { side: 4, slot: [2, 7] },
    { side: 4, slot: [3, 7] },
    { side: 4, slot: [4, 7] },
    { side: 4, slot: [5, 7] },
    { side: 4, slot: [6, 7] },
    { side: 5, slot: [1, 8] },
    { side: 5, slot: [2, 8] },
    { side: 5, slot: [3, 8] },
    { side: 5, slot: [4, 8] },
    { side: 5, slot: [5, 8] },
    { side: 5, slot: [6, 8] },
    { side: 5, slot: [7, 8] },
  ],
}

export const SHELL_ELECTRON_MAX: Record<number, number> = {
  1: 2,
  2: 8,
  3: 18,
  4: 32,
  5: 32,
  6: 18,
  7: 8,
}

export type ElectronShellLayout = {
  shell: number
  count: number
}

export function getElectronShellLayout(electronCount: number) {
  let shell = 1
  let remaining = electronCount
  let layout: Array<ElectronShellLayout> = []
  while (remaining > 0) {
    let max = SHELL_ELECTRON_MAX[shell]
    if (max >= remaining) {
      layout.push({ shell, count: remaining })
      break
    } else {
      layout.push({ shell, count: max })
      remaining -= max
    }
    shell++
  }
  console.log('layout', layout)
  return layout
}
