export const TETRAHEDRAL_PERIODIC_TABLE = {
  f: [
    ['la', 'ac'],
    ['ce', 'th'],
    ['pr', 'pa'],
    ['nd', 'u'],
    ['pm', 'np'],
    ['sm', 'pu'],
    ['eu', 'am'],
    ['gd', 'cm'],
    ['tb', 'bk'],
    ['dy', 'cf'],
    ['ho', 'es'],
    ['er', 'fm'],
    ['tm', 'md'],
    ['yb', 'no'],
  ],
  d: [
    ['sc', 'y', 'lu', 'lr'],
    ['ti', 'zr', 'hf', 'rf'],
    ['v', 'nb', 'ta', 'db'],
    ['cr', 'mo', 'w', 'sg'],
    ['mn', 'tc', 're', 'bh'],
    ['fe', 'ru', 'os', 'hs'],
    ['co', 'rh', 'lr', 'mt'],
    ['ni', 'pd', 'pt', 'ds'],
    ['cu', 'ag', 'au', 'rg'],
    ['zn', 'cd', 'hg', 'cn'],
  ],
  p: [
    ['b', 'al', 'ga', 'in', 'tl', 'nh'],
    ['c', 'si', 'ge', 'sn', 'pb', 'fl'],
    ['n', 'p', 'as', 'sb', 'bi', 'mc'],
    ['o', 's', 'se', 'te', 'po', 'lv'],
    [/*'h',*/ 'f', 'cl', 'br', 'i', 'at', 'ts'],
    [/*'he',*/ 'ne', 'ar', 'kr', 'xe', 'rn', 'og'],
  ],
  s: [
    ['h', 'li', 'na', 'k', 'rb', 'cs', 'fr', 'uue'],
    ['he', 'be', 'mg', 'ca', 'sr', 'ba', 'ra', 'ubn'],
  ],
}
